### PR TITLE
Add linting

### PR DESCRIPTION
**Pull request by edouardmenayde**
Hello :-)

I think we all agree we should lint all of our node projects.
This this is a first step in this direction.
There are still some gotchas to fix : we depend on spoonx-tools which depends itself on aurelia-tools which requires eslint-babel...

@RWOverdijk I added a travis ci file thus it would be cool if you could enable travis for this project :)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
I do agree. Completely. I see some functional stuff changed, so I'll have to review this thoroughly. Have you tested it?

**Comment by edouardmenayde** [comment]
No I was hoping to do that after having heard back from you about the few challenges using the current eslint configuration poses : mainly the current one is based on aurelia one thus makes use use eslint-babel as a dependency.
One way might be to change spoonx-tools repository scope and add a .eslintrc.node.json configuration ? 
Also that would be cool if you could enable travis just to see if it works.
My hope is to create a standard `.travis.eslint.node.yml` along a bit of doc so that we can easily use eslint + travis in all of our current and future projects.

**Comment by RWOverdijk** [comment]
Enabled. Push to trigger? :)

**Comment by RWOverdijk** [comment]
I think you can use the gulpfile from spoonx-tools for linting.

**Comment by RWOverdijk** [comment]
Looking goooooood

**Comment by RWOverdijk** [comment]
All that's left is testing then I suppose. I'll give it a go when I work on the server again!

**Pull request closed without merging**
